#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require("simple-uci").cursor()

local wg_enabled = uci:get_bool('wireguard', 'mesh_vpn', 'enabled') or false
local privkey = uci:get("wireguard", "mesh_vpn", "privatekey") or ""

local function valid_wireguard_key(wireguard_key)
	return wireguard_key and wireguard_key:match("^" .. ("[%a%d+/]"):rep(42) .. "[AEIMQUYcgkosw480]=$")
end

if not valid_wireguard_key(privkey) then
	privkey = ""
end

-- Clean up previous configuration
uci:delete_all('wireguard', 'peer', function(peer)
	return peer.preserve ~= '1'
end)

-- Delete unused configurations from older versions
uci:delete("wireguard", "mesh_vpn", "iface")
uci:delete("wireguard", "mesh_vpn", "limit")
uci:delete("wireguard", "mesh_vpn", "broker")

local mesh_enabled = uci:get_bool('gluon', 'mesh_vpn', 'enabled') -- default
	or uci:get_bool('fastd', 'mesh_vpn', 'enabled') --migration
	or wg_enabled -- specific config

uci:section("wireguard", "wireguard", "mesh_vpn", {
	enabled = mesh_enabled,
	privatekey = privkey,
})

-- TODO: consider removing wireguard.peer and using site directly
for name, peer in pairs(site.mesh_vpn.wireguard.peers()) do
	uci:section("wireguard", "peer", "peer_" .. name, {
		enabled = true,
		endpoint = peer.endpoint,
		publickey = peer.publickey,
		link_address = peer.link_address,
	})
end

uci:save('wireguard')
