#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

-- migrate older ffac-eol-ssid version with manual eol-wifi.ssid.disabled=1
if uci:get('eol-wifi', 'ssid') ~= nil then
    local deprecated_ssid_enabled = not uci:get_bool('eol-wifi', 'ssid', 'disabled')
    uci:set('eol-ssid', 'settings', 'enabled', deprecated_ssid_enabled)
    uci:save('eol-ssid')
    os.remove('/etc/config/eol-wifi')
end

if not site.eol_ssid.enabled(false) -- disabled for site/domain
or uci:get('eol-ssid', 'settings', 'enabled') == 0 -- present & disabled on router
then
    os.exit(0) -- do not change SSID
end

local eol_wifi_ssid = site.eol_ssid.ssid()

-- Change client radio ssid
uci:set('wireless', 'client_radio0', 'ssid', eol_wifi_ssid)
uci:save('wireless')
