#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local site = require 'gluon.site'

-- TODO: maybe restrict multicast to mesh?
-- TODO: userpeers with user prefix (u_) in id plus config-mode webui for that
  -- similar to static dns list field

if site.mesh.yggdrasil.enabled(false) then
  os.execute('/etc/init.d/yggdrasil enable')

  uci:delete_all('yggdrasil', 'peer', function(peer)
    return peer['.name']:match("^s_[0-9]+")
  end)

  for index, peer in pairs(site.mesh.yggdrasil.peers({})) do
    uci:section('yggdrasil', 'peer', 's_' .. index, {
      uri = peer
    })
  end
else
  os.execute('/etc/init.d/yggdrasil disable')
end

uci:save('yggdrasil')
