#!/bin/sh /etc/rc.common

# Only required for OpenWrt 19.07 and below.
# usbmuxd ships without it's own init script
# in those versions.

START=95

USE_PROCD=1
PROG=/usr/sbin/usbmuxd

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal $PROG
}
