#!/bin/sh
TTYPATH="/sys${DEVPATH}/tty"
LOCKPATH="/tmp/update-location-gps"

ENABLED=$(uci get update-location-gps.settings.enabled)

if [ "${ACTION}" = "bind" ]; then
	[ "${ENABLED}" != "1" ] && exit 0
	test -e "${LOCKPATH}" && exit 0
	if test -e  "${TTYPATH}"; then
		TTY_NAME=$(find "${TTYPATH}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sed -n 's|.*/tty/||p')
		logger -t hotplug "USB GPS device was plugged in"
		echo "${DEVPATH}" > "${LOCKPATH}"
		echo "*/5 * * * *  /usr/bin/update-location-gps /dev/${TTY_NAME} | logger -t update-location-gps" > "/usr/lib/micron.d/update-location-gps"
		/etc/init.d/micrond restart
	fi
fi

if [ "${ACTION}" = "unbind" ]; then
	if [ "${DEVPATH}" = "$(cat ${LOCKPATH})" ]; then
		logger -t hotplug "USB GPS device was removed"
		rm -f "/usr/lib/micron.d/update-location-gps"
		/etc/init.d/micrond restart
		rm "${LOCKPATH}"
	fi
fi