#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG='/usr/bin/gluon-wan /usr/sbin/nodeconfig.sh'

start_service() {
	sleep 30
	logger -t nodeconfig:init.d Starting Service
        procd_open_instance
        procd_set_param command $PROG
        procd_set_param respawn
        procd_set_param stderr 0
        #procd_set_param limits core="unlimited"  #TODO set ulimit 
        procd_set_param pidfile /var/run/nodeconfig.pid
        procd_close_instance
}
