#!/usr/bin/lua

local site = require 'gluon.site'

local uci = require('simple-uci').cursor()

if site.ssid_changer ~= nil then
	local site_enabled = site.ssid_changer.enabled() or '1'

	uci:section('ssid-changer', 'settings', 'settings', {
		enabled           = uci:get('ssid-changer', 'settings', 'enabled') or site_enabled,
		switch_timeframe  = site.ssid_changer.switch_timeframe() or '30',
		prefix            = site.ssid_changer.prefix() or 'FF_Offline_',
		suffix            = site.ssid_changer.suffix() or 'nodename',
		tq_limit_enabled  = site.ssid_changer.tq_limit_enabled() or false,
		tq_limit_max      = site.ssid_changer.tq_limit_max() or 45,
		tq_limit_min      = site.ssid_changer.tq_limit_min() or 35,
	})
	-- these settings are no longer evaluated, drop them from already deployed configs
	uci:delete('ssid-changer', 'settings', 'first')
	uci:delete('ssid-changer', 'settings', 'prefix_owe')
	uci:save('ssid-changer')
end
