#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG='/usr/bin/gluon-wan /usr/sbin/nodeconfig.sh'

start_service() {
        procd_open_instance
        procd_set_param command $PROG
        procd_set_param respawn
        procd_set_param stderr 1
        #procd_set_param limits core="unlimited"  #TODO set ulimit 
        procd_set_param pidfile /var/run/nodeconfig.pid
        procd_close_instance
}
