--[[
	Self-check for the config-mode capability, against a fixture the server
	produced. Run with: lua tests/capability_test.lua

	The fixture is generated by the provisioning server's own signing code, so
	this checks the two ends agree on the thing that is easiest to get subtly
	wrong and hardest to notice: which bytes are signed. The stub records what
	the node hands to openssl and the test asserts it is exactly the payload
	the server signed, and exactly 64 signature bytes.

	The signature arithmetic itself is one library call on each side. Checking
	that for real needs lua-openssl 0.11.1 on a node - 0.9.2, which older
	images carry, has no Ed25519 case and refuses with "invalid digest".
]]

local dir = arg[0]:match('^(.*)/[^/]*$') or '.'
local script = dir .. '/../luasrc/usr/lib/lua/gluon/config-mode/runtime/auth/proxy.lua'

-- fixture ---------------------------------------------------------------

local function slurp(path)
	local f = assert(io.open(path), path .. ' is missing')
	local d = f:read('*a')
	f:close()
	return d
end

-- a fixture small enough to pick apart without a JSON library on the host
local raw = slurp(dir .. '/capability_fixture.json')
local function field(name)
	return (raw:match('"' .. name .. '"%s*:%s*"(.-)"'):gsub('\\n', '\n'))
end

local FIXTURE = {
	pubkey = field('pubkey'),
	capability = field('capability'),
	node_id = field('node_id'),
	identity = field('identity'),
	signed_payload = field('signed_payload'),
	other_node = field('other_node'),
	wrong_key_capability = field('wrong_key_capability'),
}

-- stubs -----------------------------------------------------------------

local config = {
	['gluon-config-mode-remote'] = { remote = { pubkey = FIXTURE.pubkey } },
}

local cursor = {}
function cursor:get(c, s, o)
	local sec = config[c] and config[c][s]
	return sec and sec[o] or nil
end

package.preload['simple-uci'] = function()
	return { cursor = function() return cursor end }
end

package.preload['gluon.util'] = function()
	return { node_id = function() return FIXTURE.node_id end }
end

package.preload['luci.jsonc'] = function()
	return {
		parse = function(text)
			-- enough of a parser for the flat claim a capability carries
			local claim = {}
			for key, value in text:gmatch('"(%w+)"%s*:%s*"([^"]*)"') do
				claim[key] = value
			end
			for key, value in text:gmatch('"(%w+)"%s*:%s*(%d+)') do
				claim[key] = tonumber(value)
			end
			return claim
		end,
	}
end

-- what the node handed to openssl, so the test can check it is the right bytes
local seen = {}
local accept = true

package.preload['openssl'] = function()
	return {
		base64 = function(value, encode)
			assert(encode == false, 'the node must be decoding here, not encoding')
			-- luaposix-free base64 decode, enough for the fixture
			local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
			value = value:gsub('[^' .. b .. '=]', '')
			return (value:gsub('=', ''):gsub('.', function(c)
				local i = (b:find(c) - 1)
				local bits = ''
				for p = 6, 1, -1 do bits = bits .. (i % 2 ^ p - i % 2 ^ (p - 1) > 0 and '1' or '0') end
				return bits
			end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(byte)
				if #byte ~= 8 then return '' end
				local c = 0
				for i = 1, 8 do c = c + (byte:sub(i, i) == '1' and 2 ^ (8 - i) or 0) end
				return string.char(c)
			end))
		end,
		pkey = {
			read = function(pem)
				seen.pem = pem
				return {
					verify = function(_, data, signature)
						seen.data = data
						seen.signature = signature
						return accept
					end,
				}
			end,
		},
	}
end

-- run -------------------------------------------------------------------

local method = assert(loadfile(script))()

local http = {}
function http:getheader(name) return self.headers[name] end
function http:hasheader(name) return self:getheader(name) ~= nil end

local function ask(capability)
	http.headers = { X_GLUON_CONFIG_ACCESS = capability }
	return method.authorize(http)
end

local function eq(got, want, what)
	assert(got == want, string.format('%s: got %s, want %s', what,
		tostring(got), tostring(want)))
end

-- the happy path
local err, res = ask(FIXTURE.capability)
eq(err, nil, 'a good capability is accepted')
eq(res.identity, FIXTURE.identity, 'identity')

-- and it checked the right thing
eq(seen.pem, FIXTURE.pubkey, 'the key it verified against')
eq(seen.data, FIXTURE.signed_payload,
	'the node must verify over the encoded payload, exactly as the server signed it')
eq(#seen.signature, 64, 'an Ed25519 signature is 64 bytes')

-- a capability naming another node must not open this one: the whole point
local other_node_id = FIXTURE.node_id
package.loaded['gluon.util'] = nil
package.preload['gluon.util'] = function()
	return { node_id = function() return FIXTURE.other_node end }
end
method = assert(loadfile(script))()
err = ask(FIXTURE.capability)
assert(err and err:match('is for'), 'a capability for another node was accepted: '
	.. tostring(err))

package.loaded['gluon.util'] = nil
package.preload['gluon.util'] = function()
	return { node_id = function() return other_node_id end }
end
method = assert(loadfile(script))()

-- a signature that does not check out
accept = false
err = ask(FIXTURE.capability)
assert(err and err:match('not signed'), 'a bad signature was accepted: ' .. tostring(err))
accept = true

-- nothing presented at all
eq(method.detect(setmetatable({ headers = {} }, { __index = http })), false,
	'no header means this method does not apply')
err = ask(nil)
assert(err and err:match('no capability'), 'a missing capability was accepted')

-- malformed input must read as refused, never as a crash
for _, nonsense in ipairs({ '', 'nope', 'v1.only-two', 'v2.a.b', 'v1..' }) do
	err = ask(nonsense)
	assert(err, 'accepted nonsense: ' .. nonsense)
end

-- an expired one
config['gluon-config-mode-remote'].remote.pubkey = FIXTURE.pubkey
local real_time = os.time
os.time = function() return 4102444800 end -- luacheck: ignore
err = ask(FIXTURE.capability)
os.time = real_time -- luacheck: ignore
assert(err and err:match('expired'), 'an expired capability was accepted: ' .. tostring(err))

-- a node that was never given a key must refuse rather than let anyone in
config['gluon-config-mode-remote'].remote.pubkey = ''
err = ask(FIXTURE.capability)
assert(err and err:match('config access key'), 'a keyless node accepted a capability')

print('ok')
