#!/usr/bin/lua

local uci = require('simple-uci').cursor()

uci:section('firewall','rule','mesh_ddhcpd',{
  name = 'mesh_ddhcpd',
  src = 'mesh',
  family = 'ipv6',
  dest_port = '1234',
  proto = 'udp',
  target = 'ACCEPT',
})

uci:section('firewall','rule','mesh_d2d',{
  name = 'mesh_d2d',
  src = 'mesh',
  family = 'ipv6',
  dest_port = '1235',
  proto = 'udp',
  target = 'ACCEPT',
})

uci:section('firewall','rule','client_dhcp',{
  name = 'client_dhcp',
  src = 'loc_client',
  family = 'ipv4',
  dest_port = '67',
  proto = 'udp',
  target = 'ACCEPT',
})

uci:save('firewall')
