#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local dns = site.dns({})
local dnsmasq = uci:get_first('dhcp', 'dnsmasq')

local function get_mem_total()
	for line in io.lines('/proc/meminfo') do
		local match = line:match('^MemTotal:%s+(%d+)')
		if match then
			return tonumber(match)
		end
	end
end

-- Remove unbound default config
local unbound_section = uci:get_first('unbound', 'unbound')
if unbound_section ~= nil then
	uci:delete('unbound', unbound_section)
end

uci:foreach('unbound', 'zone', function(zone)
	uci:delete(zone['.name'])
end)

-- Disable the dnsmasq resolver
os.execute('/etc/init.d/dnsmasq disable')

-- Create unbound configuration
uci:section('unbound', 'unbound', 'unbound', {
	add_extra_dns = '1',
	add_local_fqdn = '0',
	add_wan_fqdn = '0',
	interface_auto = '1',
	listen_port = '53',
	localservice = '0',
	rebind_protection = '0',
	resource = 'tiny',
})

-- Create forwarding zone
uci:section('unbound', 'zone', 'forward_zone', {
	enabled = '1',
	fallback = '0',
	zone_name = {'.'},
	zone_type = 'forward_zone',
	server = dns.servers
})

if get_mem_total() > 64*1024 then
	uci:set('unbound', 'unbound', 'resource', 'small')
end

uci:commit('unbound')
