#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local dns = site.dns({})

local function get_mem_total()
	for line in io.lines('/proc/meminfo') do
		local match = line:match('^MemTotal:%s+(%d+)')
		if match then
			return tonumber(match)
		end
	end
end

-- Remove unbound default config
local unbound_section = uci:get_first('unbound', 'unbound')
if unbound_section ~= nil then
	uci:delete('unbound', unbound_section)
end

uci:foreach('unbound', 'zone', function(zone)
	uci:delete('unbound', zone['.name'])
end)

-- Disable the dnsmasq resolver
os.execute('/etc/init.d/dnsmasq disable')

-- Create unbound configuration
uci:section('unbound', 'unbound', 'unbound', {
	add_extra_dns = '1',
	add_local_fqdn = '0',
	add_wan_fqdn = '0',
	interface_auto = '1',
	listen_port = '53',
	localservice = '0',
	rebind_protection = '0',
	resource = 'tiny',
})

-- Create forwarding zone
uci:section('unbound', 'zone', 'forward_zone', {
	enabled = '1',
	fallback = '0',
	zone_name = {'.'},
	zone_type = 'forward_zone',
	server = dns.servers
})

-- Configure operation with DoT upstream
local dot_servers = site.unbound.dot.servers()
if dot_servers ~= nil then
	-- Remove existing server list
	uci:delete('unbound', 'forward_zone', 'server')

	-- Add DoT servers
	for _, v in pairs(dot_servers) do
		local hostname = v['hostname']
		local addresses = v['addresses']
		local port = v['port'] or 853

		for _, address in ipairs(addresses) do
			local entry = address .. '@' .. port .. '#' .. hostname
			uci:set('unbound', 'forward_zone', 'server', {entry})
		end
		uci:set('unbound', 'forward_zone', 'tls_upstream', 1)
	end

	-- DoT needs a valid NTP time in order to verify the certificates
	-- Add zones for NTP servers which will be resolved using plain DNS
	local ntp_servers = site.ntp_servers()
	if ntp_servers ~= nil then
		uci:section('unbound', 'zone', 'ntp_zone', {
			enabled = '1',
			fallback = '0',
			zone_name = ntp_servers,
			zone_type = 'forward_zone',
			server = dns.servers
		})
	end
end

if get_mem_total() > 64*1024 then
	uci:set('unbound', 'unbound', 'resource', 'small')
end

uci:commit('unbound')
