#!/usr/bin/lua

local site = require 'gluon.site'

local cronfile = "/usr/lib/micron.d/gluon-scheduled-sysupgrade"

-- Check if domain switch is scheduled
if site.scheduled_sysupgrade() == nil then
	-- In case no domain switch is scheduled, remove cronfile
	os.remove(cronfile)
	os.exit(0)
end

-- Only in case domain switch is scheduled
local f = io.open(cronfile, "w")
f:write("* * * * *  /usr/bin/gluon-check-available\n")
f:write("*/5 * * * *  /lib/gluon/scheduled-sysupgrade/do-sysupgrade\n")
f:close()
