#!/usr/bin/lua

local site = require 'gluon.site'
local vpn_core = require 'gluon.mesh-vpn'
local sysconfig = require 'gluon.sysconfig'
local ssl = require 'openssl'

local uci = require('simple-uci').cursor()

-- https://stackoverflow.com/a/4991602/3990041
local function file_exists(name)
	local f = io.open(name, 'r')
	if f ~= nil then
		io.close(f)
		return true else return false
	end
end

local vpn = {
	enabled = vpn_core.enabled(),

	client = true,
	dev = vpn_core.get_interface(),
	dev_type = 'tap',
	-- mesh_vpn_dns.nft redirects dns from this group to the wan dnsmasq on
	-- :54. without it the vpn server's name is resolved over the mesh, so
	-- the tunnel that carries the mesh depends on the mesh already working
	group = 'gluon-mesh-vpn',
	-- SO_MARK on the transport socket; wan4_lookup/wan6_lookup route it out
	-- the wan. openvpn parses this as an integer, not as a mark/mask pair
	mark = '1'
}

for key, value in pairs(site.mesh_vpn.openvpn.config()) do
	vpn[key] = value
end

-- if mesh_vpn is on but we have no key, even tho we need one then we can't proceed
if vpn.key ~= nil and not file_exists(vpn.key) then
	if site.mesh_vpn.openvpn.self_signed(true) then
		local name = ssl.x509.name.new{
			{ C = 'CN'},
			{ O = 'gluon' },
			{ CN = sysconfig.primary_mac }
		}

		local key = ssl.pkey.new()

		local cert = ssl.x509:new()
		cert:notbefore(os.time())
		cert:notafter(os.time() + 10 * 365 * 24 * 60)
		cert:subject(name)
		cert:sign(key, name)

		local certf = io.open(vpn.cert, 'w+')
		certf:write(cert:export())
		certf:close()

		local keyf = io.open(vpn.key, 'w+')
		keyf:write(key:export())
		keyf:close()
	else
		vpn.enabled = false
	end
end

if vpn.ca ~= nil and not file_exists(vpn.ca) then
	local caf = io.open(vpn.ca, 'w+')
	caf:write(site.mesh_vpn.openvpn.ca())
	caf:close()
end

uci:delete('openvpn', 'mesh_vpn')
if vpn.enabled then
	uci:section('openvpn', 'openvpn', 'mesh_vpn', vpn)
end

-- superseded by the mark above: that one is set on the socket itself, so it
-- does not have to guess the port the site dials out on
uci:delete('firewall', 'openvpn_mark')

uci:save('openvpn')
uci:save('firewall')
