#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

NAME=ddhcpd
DAEMON=/usr/sbin/ddhcpd
MAXDELAY=10

validate_section_ddhcpd() {
  uci_validate_section "$NAME" ddhcpd settings \
  'dhcp_interface:string:br-client' \
  'server_interface:string:br-client' \
  'block_size_pow:uinteger:2' \
  'block_timeout:uinteger:300' \
  'spare_leases:uinteger:2' \
  'tentative_timeout:uinteger:15' \
  'block_network:cidr4' \
  'dhcp_lease_time:uinteger:300' \
  'enabled:uinteger:1'
}

dhcp_option() {
  local cfg="$1" code len payload
  config_get code "$cfg" code
  config_get len "$cfg" len
  config_get payload "$cfg" payload
  procd_append_param command -o "$code:$len:$payload"
}

start_service() {
  procd_open_instance
  procd_set_param command $DAEMON -D

  config_load "${NAME}"

  validate_section_ddhcpd || {
    echo "validation failed"
    return 1
  }

  [ "$enabled" -eq 0 ] && {
    return 0
  }

  procd_append_param command -s "$spare_leases"
  procd_append_param command -b "$block_size_pow"
  procd_append_param command -B "$block_timeout"
  procd_append_param command -c "$dhcp_interface"
  procd_append_param command -i "$server_interface"
  procd_append_param command -N "$block_network"
  procd_append_param command -t "$tentative_timeout"
  procd_append_param command -H "/etc/ddhcpd.hook"
  config_foreach dhcp_option dhcp_option
  [[ -f /lib/gluon/ddhcpd/arguments ]] && procd_append_param command $(/lib/gluon/ddhcpd/arguments)
  procd_set_param respawn
  procd_set_param netdev "$dhcp_interface"
  [ "$dhcp_interface" == "$server_interface" ] || procd_append_param netdev "$server_interface"
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers() {
  procd_add_config_trigger "config.change" "ddhcpd" /etc/init.d/ddhcpd restart
  procd_add_interface_trigger "interface.*" "br-client" /etc/init.d/ddhcpd restart
}
