#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local site_config_server = site.parker.config_server()
local site_config_pubkey = site.parker.config_pubkey()
uci:section('parker', 'nodeconfig', 'nodeconfig',
	{
		config_server = site_config_server,
		config_pubkey = site_config_pubkey,
	}
)
uci:save('parker')
